name: vips-nip2 
version: 'master'
summary: An image-processing spreadsheet.
description: |
  nip2 is half-way between a spreadsheet and a paint program. 
  It's terrible for retouching photographs, but very handy for automating image 
  processing tasks. 

  It can process multi-gigabyte images efficiently. It has good support for 
  scientific image formats. It's much faster and more flexible than tools like 
  ImageJ. 

  This snap is git master nip2 built with git master libvips. 

grade: devel 
confinement: strict

apps:
  nip2:
    command:  desktop-launch nip2
    plugs: [x11, home, gsettings]

parts:
  vips-part:
    source: https://github.com/jcupitt/libvips
    source-branch: master
    source-type: git
    plugin: autotools
    build-packages:
        -    gobject-introspection
        -    intltool
        -    libgirepository1.0-dev
        -    libglib2.0-dev
        -    libfftw3-dev
        -    libexpat1-dev
        -    libxml2-dev 
        -    libjpeg-turbo8-dev
        -    libtiff5-dev
        -    libopenslide-dev
        -    libopenexr-dev
        -    libcfitsio-dev
        -    libmatio-dev
        -    libgif-dev
        -    libpoppler-dev
        -    librsvg2-dev
        -    libmagickcore-dev
        -    libexif-dev
        -    libgsf-1-dev
        -    liblcms2-dev
        -    libpng-dev
        -    libpango1.0-dev
        -    liborc-0.4-dev
        -    libwebp-dev

  nip2-part:
    source: https://github.com/jcupitt/nip2
    source-branch: master
    source-type: git
    plugin: autotools
    build-packages:
        -    gobject-introspection
        -    intltool
        -    libgirepository1.0-dev
        -    libglib2.0-dev
        -    libgtk2.0-dev
        -    libx11-dev
        -    libxml2-dev
        -    flex
        -    bison
        -    libfftw3-dev
        -    libgoffice-0.8-dev
        -    libgsl-dev
        -    libgvc6
    after: [desktop-gtk2, vips-part]

